package spatial

import (
	"errors"
	"time"
)

var (
	ErrAssetGenerationJobNotFound                = errors.New("spatial: asset generation job not found")
	ErrAssetGenerationJobNotClaimable            = errors.New("spatial: asset generation job not currently claimable")
	ErrAssetGenerationRequestFingerprintConflict = errors.New("spatial: clientRequestId already used for a different asset generation request")
	ErrAssetGenerationSourceInvalid              = errors.New("spatial: source image is invalid for asset generation")
	ErrAssetGenerationNotConfigured              = errors.New("spatial: asset generation support not configured")
)

// AssetGenerationSourceKind discriminates where a job's source image comes
// from — the original RP4E0 public route (a directly-uploaded capture
// artifact) or RP4E2's internal design-reference path (a reference image
// generated by the Python service and stored under R2 by
// DesignGenerationAttempt's own reference phase). A job's source is always
// exactly one of these; there is no "both" case.
type AssetGenerationSourceKind string

const (
	AssetGenerationSourceKindCaptureArtifact AssetGenerationSourceKind = "capture_artifact"
	AssetGenerationSourceKindDesignReference AssetGenerationSourceKind = "design_reference"
)

// AssetGenerationSourceRef identifies the job's source image regardless of
// kind. Exactly one of ArtifactID/DesignAttemptID+ObjectKey is populated,
// matching Kind. A pre-existing Mongo document with no `source` field
// decodes as {Kind: capture_artifact, ArtifactID: <the old sourceArtifactId
// field>} — see fromAssetGenerationJobDoc's compatibility handling.
type AssetGenerationSourceRef struct {
	Kind AssetGenerationSourceKind

	// Populated when Kind == capture_artifact.
	ArtifactID string

	// Populated when Kind == design_reference.
	DesignAttemptID string
	ObjectKey       string // the reference image's R2 key — resolved to a short-lived URL at submit/resume time, never stored as a URL
}

// SpatialAssetGenerationJob is the durable record of one Hunyuan
// generation attempt (RP4E0, first real implementation of M8.5C §37 for
// this job kind). Provider-call checkpoints are set in strict acquisition
// order — their PRESENCE is the state machine; see claimPhase() and
// isSafeToClaim().
type SpatialAssetGenerationJob struct {
	ID        string
	CompanyID string
	ProjectID string

	ClientRequestID    string // caller-supplied idempotency key
	RequestFingerprint string // SERVER-COMPUTED — never trusted from the client

	Source AssetGenerationSourceRef
	Seed   int64

	// Provider-call checkpoints, in strict acquisition order.
	ProviderStartedAt *time.Time // set immediately before the Gradio POST — the ZeroGPU danger-zone marker
	ProviderRequestID *string    // Gradio's event_id — set immediately after the POST returns

	// Staging checkpoint — set the instant raw bytes are durably stored,
	// BEFORE validation. Points at a staging key, never RP4D's final key.
	GeneratedObjectKey string
	GeneratedChecksum  string
	GeneratedByteCount int64

	// Result, populated only on JobExecutionCompleted.
	ResultAssetID string
	ResultVersion int

	CreatedByUserID string
	CreatedAt       time.Time

	Execution JobExecution
}

// AssetGenerationClaimPhase identifies what a worker should do once a
// claim on this job succeeds.
type AssetGenerationClaimPhase int

const (
	// ClaimPhaseStartProvider: no provider call has been attempted yet.
	// Safe to call StartShapeGeneration.
	ClaimPhaseStartProvider AssetGenerationClaimPhase = iota
	// ClaimPhaseResumeProvider: a provider event_id is already known.
	// Safe to call ResumeShapeGeneration — NEVER StartShapeGeneration
	// again.
	ClaimPhaseResumeProvider
	// ClaimPhaseResumeValidation: raw bytes are already staged. Skip the
	// provider entirely; resume from geometry validation.
	ClaimPhaseResumeValidation
)

func (j SpatialAssetGenerationJob) claimPhase() AssetGenerationClaimPhase {
	if j.GeneratedObjectKey != "" {
		return ClaimPhaseResumeValidation
	}
	if j.ProviderRequestID != nil {
		return ClaimPhaseResumeProvider
	}
	return ClaimPhaseStartProvider
}

// isSafeToClaim implements the spec's claim-safety predicate in plain Go
// (mirrored EXACTLY by the Mongo claim query's filter in
// repository_mongo.go — this function exists so the dangerous state is
// proven excluded by a pure unit test before any Mongo query is written,
// and so the two can be compared for drift in review).
func (j SpatialAssetGenerationJob) isSafeToClaim(now time.Time) bool {
	if j.Execution.leaseIsHeld(now) {
		return false
	}
	switch j.Execution.Status {
	case JobExecutionPending, JobExecutionProcessing:
		// fall through to checkpoint check below
	default:
		return false
	}
	// The one dangerous state: provider invocation started, but neither
	// the event_id nor the staged GLB is known yet. This must NEVER be
	// automatically reclaimed.
	if j.ProviderStartedAt != nil && j.ProviderRequestID == nil && j.GeneratedObjectKey == "" {
		return false
	}
	return true
}
