package composition

import (
	"context"
	"io"

	"github.com/shananth/renovation-platform/backend/internal/platform/objectstore"
)

// SpatialAssetGenerationStoreAdapter satisfies
// spatial.AssetGenerationObjectStore against a concrete
// objectstore.ObjectStore — a straight pass-through, mirroring
// SpatialVisualAssetStoreAdapter's exact shape (RP4E0). This is the
// STAGING store for raw generated bytes before validation/publication —
// a distinct key prefix from the final immutable visual-assets store.
type SpatialAssetGenerationStoreAdapter struct {
	store objectstore.ObjectStore
}

// NewSpatialAssetGenerationStagingStoreAdapter wraps store.
func NewSpatialAssetGenerationStagingStoreAdapter(store objectstore.ObjectStore) *SpatialAssetGenerationStoreAdapter {
	return &SpatialAssetGenerationStoreAdapter{store: store}
}

func (a *SpatialAssetGenerationStoreAdapter) Put(ctx context.Context, key string, content io.Reader) (int64, error) {
	return a.store.Put(ctx, key, content)
}

func (a *SpatialAssetGenerationStoreAdapter) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	return a.store.Get(ctx, key)
}
