"use client";

import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/lib/api/client";
import { PageHeader } from "@/components/layout/PageHeader";
import { Badge } from "@/components/ui/badge";

async function loadCompany(){const [company,members]=await Promise.all([apiClient.GET("/companies/me"),apiClient.GET("/companies/me/members",{params:{query:{page:1,pageSize:100}}})]);if(company.error)throw company.error;if(members.error)throw members.error;return {company:company.data,members:members.data};}
export function CompanySettings(){const query=useQuery({queryKey:["company"],queryFn:loadCompany});if(query.isLoading)return <div className="surface-card h-64 animate-pulse"/>;if(query.error||!query.data)return <div className="surface-card p-10 text-center"><h1 className="font-heading text-xl font-semibold">Company workspace unavailable</h1><p className="mt-2 text-sm text-muted-foreground">Company membership data could not be loaded.</p></div>;const {company,members}=query.data;return <div className="flex flex-col gap-5"><PageHeader title="Company" description="Contractor company and authorized workspace members"/><section className="surface-card p-5"><p className="eyebrow">Company name</p><h2 className="mt-2 font-heading text-xl font-semibold">{company.name}</h2><p className="mt-2 text-xs text-muted-foreground">Created {new Date(company.createdAt).toLocaleDateString("en-MY")}</p></section><section className="surface-card overflow-hidden"><div className="border-b p-4"><h2 className="font-heading font-semibold">Members</h2><p className="text-xs text-muted-foreground">Roles are authoritative backend membership records.</p></div><div className="table-scroll"><table className="w-full min-w-140 text-sm"><thead><tr className="border-b bg-muted/40 text-left"><th className="p-3">User</th><th>Role</th><th>Joined</th></tr></thead><tbody>{(members.items??[]).map((member)=><tr key={member.userId} className="border-b last:border-0"><td className="p-3 font-mono text-xs">{member.userId}</td><td><Badge variant="outline" className="capitalize">{member.role}</Badge></td><td>{new Date(member.createdAt).toLocaleDateString("en-MY")}</td></tr>)}</tbody></table></div></section></div>}
